### PR TITLE
#158496205 Add test coverage reporting 

### PR DESCRIPTION
**Pull request by anyric**
**What does this PR do?**

This PR adds test coverage reporting for CodeClimate

**Description of Task to be completed?**

Configure test coverage reporting for activo web

**How should this be manually tested?**

The test coverage badges on CodeClimate and the README will be updated once committed changes to a branch is build, tested and results uploaded to CodeClimate automatically.

**Any background context you want to provide?**

N/A

**What are the relevant pivotal tracker stories?**

[#158496205](https://www.pivotaltracker.com/story/show/158496205)

**Screenshots (if appropriate)**

N/A

**Questions:**

N/A

### CODE REVIEW

**Comment by kevinejiro** [comment]
Please refer to the [Engineering playbook](https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions) for the proper commit message conventions

**Comment by Chidiebube** [comment]
@anyric have you addressed the comments made especially following the standard conventions ? You were also reminded about it [here](https://github.com/andela/activo-web/pull/39) which you closed. Always ensure you adhere to teams coding standards going forward.

**Comment by code-sleuth** [comment]
LGTM

**Comment by kevinejiro** [comment]
For chores you should use [Maintains #Pivotal tracker ID] in your commit message, while [Finishes ##Pivotal tracker ID] is best for features.

**Pull request merged**
