### PR TITLE
#158869814 Move images and fonts to Cloudinary

### PR DESCRIPTION
**Pull request by Billmike**
**What does this PR do?**
Moves images and fonts to Cloudinary and update the links.

**Description of Task to be completed?**
- move images to Cloudinary
- move fonts to Cloudinary
- update image links to reflect Cloudinary URLs
- update font links to reflect Cloudinary URLs

**How should this be manually tested?**
After cloning or fetching branch, run the application. Fonts should be correctly displayed, and image assets should load properly.

**Any background context you want to provide?**
N/A

**What are the relevant pivotal tracker stories?**
[#158869814](https://www.pivotaltracker.com/story/show/158869814)

**Screenshots (if appropriate)**

screen shot 2018-07-12 at 2 24 48 pm

**Questions:**

N/A

### CODE REVIEW

**Comment by andela-kakpobome** [comment]
I'm going to give you sometime to reflect on this PR title before I attack you! @Billmike

**Comment by Billmike** [comment]
@bourgeois247 PR title fixed! 🙈

**Comment by sccofield** [comment]
@Billmike  since the URL that comes from Cloudinary is a bit long, in order to avoid breaking our max line length rule, I want to suggest the following.

1) Make use of a URL shortener like www.goo.gl to shorten our URLs first before using it on our project, but the bad side is that we will be relying on yet another third-party application.

2) Have an image file where we declare all our images, and export them to be used where ever we need them. This also makes sense since some of the images are reused more than once. 

@Billmike @bahdcoder @missating @Dammyy @kevinejiro @andela-kakpobome what are your thoughts on this.

**Comment by Billmike** [comment]
@bourgeois247 Conflicts fixed.

**Comment by Billmike** [comment]
Umm. What benefits does using a URL shortener add to the project? @sccofield Also, could you shed some more light on what your second point? Do you mean having a file locally in the application's directory for housing all image files?

**Comment by andela-kakpobome** [comment]
@sccofield I think your suggestions make a lot of sense, especially with respect to unnecessary line length. However, I'm going to make a judgement call here, and say we shouldn't invest in doing that because:

1. Like you said we'd have to rely on yet another 3rd party for that, if we go with suggestion 1
2. If we go with suggestion 2, we'd have yet another file that simply records url => variable name mappings, and that'll eventually become cognitive overhead for anyone to manage when working with image related tasks

So for those reasons, I say we move forward as is, makes sense?

**Pull request merged**
