### PR TITLE
#159759387 Setup Activo-web Sandbox

### PR DESCRIPTION
**Pull request by iidrees**
#### What does this PR do?
This PR adds a `type: approval` to the Circle CI `config.yml`  file

#### Description of Task to be completed?
- when branch with the keyword `sandbox` is created, a `sandbox` is deployed.

#### How should this be manually tested?
Testing is done by Circle CI

#### Any background context you want to provide?
Currently the job pipeline has no pause mechanism that pauses the flow whenever a sandbox branch is created so this PR ensures that there is a pause at the `release to sandbox` stage and until the pipeline is `approved to continue` then it stays paused there.

#### What are the relevant pivotal tracker stories?
[#159759387 ](https://www.pivotaltracker.com/story/show/159759387)

#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Comment by Thegaijin** [comment]
LGTM

**Comment by indungu** [comment]
LGTM

**Comment by andela-kakpobome** [comment]
@iidrees please fix conflicts

**Comment by iidrees** [comment]
@andela-kakpobome Done conflicts resolved.

**Pull request merged**
